"use client";

import { motion, useReducedMotion } from "motion/react";
import { Check, GitPullRequest, GitMerge } from "lucide-react";

/**
 * A premium, GitHub-flavored pull-request card. Used in the hero and
 * demo flow to show the "fix shipped as a PR" payoff.
 */
export function GeneratedPrCard({
  className,
}: {
  className?: string;
}) {
  const reduce = useReducedMotion();

  return (
    <motion.div
      className={className}
      // Transform-only entrance: the card is visible in server HTML (opacity
      // stays 1), so the hero's likely LCP element paints before hydration
      // and merely settles into place once JS arrives.
      initial={{ y: 30, rotateX: 8 }}
      animate={{ y: 0, rotateX: 0 }}
      transition={reduce ? { duration: 0 } : { duration: 0.8, delay: 0.3, ease: [0.16, 1, 0.3, 1] }}
      style={{ perspective: 1000 }}
    >
      <div className="glass rounded-xl shadow-2xl shadow-black/40">
        {/* Header */}
        <div className="flex items-center gap-2 border-b border-border px-4 py-3">
          <GitPullRequest className="size-4 text-signal" />
          <span className="text-sm font-medium text-fg">
            fix(seo): add canonical URLs to features pages
          </span>
          <span className="ml-auto rounded-full bg-signal/15 px-2 py-0.5 text-[11px] font-medium text-signal">
            Open
          </span>
        </div>

        {/* Meta */}
        <div className="flex items-center gap-2 px-4 py-2.5 text-xs text-fg-muted">
          <span className="font-mono text-electric-bright">
            rankforge/seo-canonical-features
          </span>
          <span className="text-fg-subtle">→ main</span>
          <span className="ml-auto text-signal">+21</span>
          <span className="text-danger">-2</span>
        </div>

        {/* Diff */}
        <div className="mx-4 mb-3 overflow-hidden rounded-md border border-border bg-code font-mono text-[11.5px] leading-relaxed">
          <div className="border-b border-border px-3 py-1.5 text-[11px] text-fg-subtle">
            app/features/layout.tsx
          </div>
          <pre className="px-3 py-2">
            <code>
              <span className="block text-fg-muted">{`  import type { Metadata } from "next";`}</span>
              <span className="block bg-signal/10 text-signal">{`+ export const metadata: Metadata = {`}</span>
              <span className="block bg-signal/10 text-signal">{`+   alternates: { canonical: "https://acme.com/features" },`}</span>
              <span className="block bg-signal/10 text-signal">{`+ };`}</span>
              <span className="block text-fg-muted">{`  export default function FeaturesLayout() {`}</span>
            </code>
          </pre>
        </div>

        {/* Checklist */}
        <div className="space-y-1.5 px-4 pb-4 text-xs text-fg-muted">
          {[
            "Canonical renders once per page",
            "Query variants resolve to canonical",
            "No change to page content",
          ].map((label) => (
            <div key={label} className="flex items-center gap-2">
              <span className="grid size-4 place-items-center rounded-full bg-signal/15">
                <Check className="size-2.5 text-signal" />
              </span>
              {label}
            </div>
          ))}
        </div>

        {/* Footer */}
        <div className="flex items-center gap-2 border-t border-border px-4 py-3 text-xs">
          <GitMerge className="size-3.5 text-violet" />
          <span className="text-fg-muted">Generated by</span>
          <span className="font-medium text-fg">RankForge</span>
          <span className="ml-auto rounded-md bg-electric px-2.5 py-1 font-medium text-white">
            Merge when ready
          </span>
        </div>
      </div>
    </motion.div>
  );
}
