import type { PullRequest } from "@/types";

/**
 * Generated pull requests. Some are open on GitHub, one is merged,
 * and the rest are "simulated" — the state RankForge shows before a
 * user clicks "Create PR" when running in suggest-only mode.
 */
export const mockPullRequests: PullRequest[] = [
  {
    id: "pr_acme_42",
    repoId: "repo_acme",
    issueIds: ["iss_acme_canonical_features"],
    number: 42,
    title: "fix(seo): add canonical URLs to features pages",
    description:
      "Adds canonical metadata to the /features segment so Google consolidates indexing signals on the clean URL instead of trailing-slash and query-string duplicates.\n\nGenerated by RankForge.",
    branchName: "rankforge/seo-canonical-features",
    baseBranch: "main",
    status: "open",
    additions: 21,
    deletions: 2,
    files: [
      {
        path: "app/features/layout.tsx",
        additions: 7,
        deletions: 0,
        diff: `@@ -1,7 +1,14 @@
 import type { Metadata } from "next";
+
+export const metadata: Metadata = {
+  alternates: {
+    canonical: "https://acme.com/features",
+  },
+};

 export default function FeaturesLayout({ children }) {`,
      },
      {
        path: "app/features/[slug]/page.tsx",
        additions: 14,
        deletions: 2,
        diff: `@@ -1,5 +1,15 @@
 import type { Metadata } from "next";
+
+export async function generateMetadata({ params }): Promise<Metadata> {
+  const { slug } = await params;
+  return { alternates: { canonical: \`https://acme.com/features/\${slug}\` } };
+}`,
      },
    ],
    checklist: [
      { label: "Canonical renders once per page", done: true },
      { label: "Query-string variants resolve to canonical", done: true },
      { label: "No change to page content", done: true },
      { label: "Re-submitted in Search Console", done: false },
    ],
    expectedImpact: "Consolidates 6 duplicate /features URLs → higher indexing efficiency.",
    risk: "low",
    url: "https://github.com/acme/acme-saas-web/pull/42",
    createdAt: "2026-06-23T09:10:00.000Z",
  },
  {
    id: "pr_acme_43",
    repoId: "repo_acme",
    issueIds: ["iss_acme_sitemap_dynamic"],
    number: 43,
    title: "fix(seo): generate sitemap for dynamic routes",
    description:
      "Adds a dynamic sitemap covering blog posts and feature pages so Google can discover all 142 indexable URLs, not just 12 static ones.\n\nGenerated by RankForge.",
    branchName: "rankforge/seo-dynamic-sitemap",
    baseBranch: "main",
    status: "draft",
    additions: 27,
    deletions: 0,
    files: [
      {
        path: "app/sitemap.ts",
        additions: 27,
        deletions: 0,
        diff: `@@ -0,0 +1,27 @@
+import type { MetadataRoute } from "next";
+import { getAllPosts } from "@/lib/posts";
+import { getAllFeatures } from "@/lib/features";
+
+const BASE = "https://acme.com";
+
+export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
+  const [posts, features] = await Promise.all([getAllPosts(), getAllFeatures()]);
+  return [{ url: BASE, priority: 1 }, /* …blog + features… */];
+}`,
      },
    ],
    checklist: [
      { label: "sitemap.xml returns 140+ URLs", done: true },
      { label: "XML validates", done: true },
      { label: "Submitted to Search Console", done: false },
    ],
    expectedImpact: "+130 discoverable URLs; faster indexing of new posts.",
    risk: "medium",
    url: "https://github.com/acme/acme-saas-web/pull/43",
    createdAt: "2026-06-23T09:24:00.000Z",
  },
  {
    id: "pr_acme_40",
    repoId: "repo_acme",
    issueIds: ["iss_acme_software_schema"],
    number: 40,
    title: "fix(seo): add SoftwareApplication schema",
    description:
      "Adds sitewide SoftwareApplication structured data describing the product, category and pricing band.\n\nGenerated by RankForge.",
    branchName: "rankforge/seo-software-application-schema",
    baseBranch: "main",
    status: "merged",
    additions: 12,
    deletions: 0,
    files: [
      {
        path: "app/layout.tsx",
        additions: 8,
        deletions: 0,
        diff: `@@ -1,4 +1,12 @@
 import { softwareApplicationJsonLd } from "@/lib/schema";
+
+const appSchema = softwareApplicationJsonLd({ name: "Acme", offersFrom: 29 });`,
      },
      {
        path: "lib/schema.ts",
        additions: 4,
        deletions: 0,
        diff: `@@ -10,0 +11,4 @@
+export function softwareApplicationJsonLd(opts) {
+  return { "@context": "https://schema.org", "@type": "SoftwareApplication", ...opts };
+}`,
      },
    ],
    checklist: [
      { label: "Rich Results Test passes", done: true },
      { label: "No layout regression", done: true },
      { label: "Merged to main", done: true },
    ],
    expectedImpact: "App-style rich-result eligibility on the homepage.",
    risk: "low",
    url: "https://github.com/acme/acme-saas-web/pull/40",
    createdAt: "2026-06-10T14:02:00.000Z",
  },
  {
    id: "pr_studio_18",
    repoId: "repo_studio",
    issueIds: ["iss_studio_org_schema"],
    number: 18,
    title: "fix(seo): add Organization schema",
    description:
      "Adds sitewide Organization structured data (name, logo, sameAs) to strengthen brand entity signals.\n\nGenerated by RankForge.",
    branchName: "rankforge/seo-organization-schema",
    baseBranch: "main",
    status: "open",
    additions: 14,
    deletions: 0,
    files: [
      {
        path: "app.vue",
        additions: 14,
        deletions: 0,
        diff: `@@ -1,4 +1,18 @@
 <script setup lang="ts">
+useHead({ script: [{ type: "application/ld+json", innerHTML: JSON.stringify({
+  "@context": "https://schema.org", "@type": "Organization",
+  name: "Northstar Studio", url: "https://studio.northstar.dev",
+}) }] });
 </script>`,
      },
    ],
    checklist: [
      { label: "Rich Results Test passes", done: true },
      { label: "sameAs profiles verified", done: false },
    ],
    expectedImpact: "Stronger brand entity + knowledge-panel eligibility.",
    risk: "low",
    url: "https://github.com/northstar/studio-landing/pull/18",
    createdAt: "2026-06-21T12:40:00.000Z",
  },
  {
    id: "pr_northstar_robots",
    repoId: "repo_northstar",
    issueIds: ["iss_ns_robots_old_sitemap"],
    number: 0,
    title: "fix(seo): correct sitemap URL in robots.txt",
    description:
      "Updates the Sitemap directive to the live /sitemap-index.xml so crawlers stop hitting a 404.\n\nGenerated by RankForge.",
    branchName: "rankforge/seo-fix-robots-sitemap",
    baseBranch: "main",
    status: "simulated",
    additions: 1,
    deletions: 1,
    files: [
      {
        path: "public/robots.txt",
        additions: 1,
        deletions: 1,
        diff: `@@ -2,5 +2,5 @@
-Sitemap: https://docs.northstar.dev/sitemap-legacy.xml
+Sitemap: https://docs.northstar.dev/sitemap-index.xml`,
      },
    ],
    checklist: [
      { label: "Sitemap line resolves with 200", done: false },
      { label: "Ready to open on GitHub", done: false },
    ],
    expectedImpact: "Crawlers rediscover the live sitemap (386 URLs).",
    risk: "low",
    url: null,
    createdAt: "2026-06-22T17:30:00.000Z",
  },
];

export function getPullRequest(id: string): PullRequest | undefined {
  return mockPullRequests.find((p) => p.id === id);
}

export function getPullRequestsForRepo(repoId: string): PullRequest[] {
  return mockPullRequests.filter((p) => p.repoId === repoId);
}

export function getPullRequestForIssue(issueId: string): PullRequest | undefined {
  return mockPullRequests.find((p) => p.issueIds.includes(issueId));
}
