import type { PullRequest, Repository, SeoIssue } from "@/types";

/**
 * Build a PullRequest object from an issue's suggested fix. Shared by the
 * PR-preview page (id `preview_*`, never persisted) and the
 * createPullRequest server action (real id, persisted with status
 * "simulated" until GitHub is wired).
 */
export function buildPrFromIssue(
  issue: SeoIssue,
  repo: Repository | null,
  id: string,
): PullRequest {
  const fix = issue.suggestedFix;
  return {
    id,
    repoId: issue.repoId,
    issueIds: [issue.id],
    number: 0,
    title: fix.prTitle,
    description: `${fix.prDescription}\n\nGenerated by RankForge.`,
    branchName: fix.branchName,
    baseBranch: repo?.defaultBranch ?? "main",
    status: "simulated",
    files: fix.filesChanged.map((path, idx) => ({
      path,
      additions: 0,
      deletions: 0,
      // The suggested fix carries a single combined diff; attach it to the
      // first file and show the rest as references.
      diff: idx === 0 ? fix.diff : `# ${path}\n# (see combined diff above)`,
    })),
    additions: 0,
    deletions: 0,
    checklist: fix.validationSteps.map((label) => ({ label, done: false })),
    expectedImpact: `${issue.impact} impact · ${issue.category}`,
    risk: issue.risk,
    url: null,
    createdAt: new Date().toISOString(),
  };
}
