import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { PageHeader } from "@/components/app/page-header";
import { PrPreview } from "@/components/app/pr-preview";
import { getPullRequest, getRepository } from "@/lib/data";

export async function generateMetadata({
  params,
}: {
  params: Promise<{ id: string }>;
}): Promise<Metadata> {
  const { id } = await params;
  const pr = await getPullRequest(id);
  return { title: pr ? pr.title : "Pull request" };
}

export default async function PullRequestPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const pr = await getPullRequest(id);
  if (!pr) notFound();
  const repo = await getRepository(pr.repoId);

  return (
    <>
      <PageHeader
        breadcrumbs={[
          { label: "Pull requests", href: "/pull-requests" },
          { label: pr.number > 0 ? `#${pr.number}` : "Draft" },
        ]}
        title={pr.title}
        description={
          repo ? `${repo.fullName} · generated by RankForge` : undefined
        }
      />
      <PrPreview pr={pr} repo={repo} />
    </>
  );
}
